### ISSUE TITLE
Freeze Python package dependencies (camkes-deps currently breaks)

### ISSUE THREAD

**Issue by robby-phd** [seL4/seL4-CAmkES-L4v-dockerfiles#41]
camkes-deps depends on simpleeval, whose latest version currently cannot be installed (see danthedeckie/simpleeval#90).

This affected the CASE Vagrant/VirtualBox VM setup:

https://github.com/sireum/case-env/runs/3568671703?check_suite_focus=true#step:5:6023

As a workaround, we patched basetools.sh and sel4.sh to keep the CASE VM reproducible:

https://github.com/sireum/case-env/commit/31a85759c8a0892fb8cae280e4bdebc004256fb5

One approach is to freeze seL4+CAmkES Python package dependencies to prevent similar issues to crop up (similar to using Debian snapshot).

**Comment by lsf37** [comment]
Hey @szhuang, do you mean the automated docker update? That is currently not running, because Debian stable has changed and the current docker files don't build any more (#39 will fix this, but is blocked on a bug in sel4test).
