### ISSUE TITLE
Do not run Authenticate and Push on forks

### ISSUE THREAD

**Issue by axel-h** [seL4/seL4-CAmkES-L4v-dockerfiles#51]
Follow-up from #49, do not run Authenticate and Push on forks because this always fails due to missing credentials.
Maybe we can check if `secrets.DOCKER_USER` and `secrets.DOCKER_TOKEN` is set. Do forks could use their own credentials here - but this would require putting allowing to customize the hard-coded `trustworthysystems` then also.

**Comment by lsf37** [comment]
Good point. As a first step, I'd say we should just not deploy from forks for now, and we can add more variables if someone has a need.

In case this is bothering you right now: you can now manually selectively turn off specific workflows on GitHub in the Actions panel.
